import { generateAccountNumber, checkIfAccountExists, findAccountIndex, getCurrentDateAndTime } from "../utils/helper.js";
import { updateAccounts, updateTransactions } from "../utils/jsonHandler.js";
import { InvalidUserNameEntered, InvalidAccountTypeEntered, InvalidAmountEntered, InvalidAccountEntered, InvalidWithdrawalAmount } from "./errors.js";
import { Transaction } from "./Transaction.js";

export let accountsArray = [];

/**
 * Account Model
 * 
 * Handles:
 * - Account creation
 * - Balance updates
 * - Transfers between accounts
 * - Viewing accounts
 */
export class Account {
    /**
     * Creates a new account instance.
     * 
     * @param {string} userName - Username associated with the account.
     * @param {string} accountType - The type of account (Investment, Banking, etc.).
     * @param {number} balance - The balance for a new account is set to 0.
     * @param {number} accountNumber - The new account number that gets autogenerated
     */
    constructor(userName, accountType, balance = 0, accountNumber = generateAccountNumber()) {
        this.accountNumber = accountNumber;
        this.userName = userName;
        this.balance = balance;
        this.accountType = accountType;
    }

    set userName(userNameValue) {
        if (!userNameValue?.trim()) throw new InvalidUserNameEntered();
        this._userName = userNameValue;
    }

    set accountType(accountTypeValue) {
        if (!accountTypeValue?.trim()) throw new InvalidAccountTypeEntered();
        this._accountType = accountTypeValue;
    }

    get userName() { return this._userName; }
    get accountType() { return this._accountType; }

    // Make JSON clean (no underscores)
    toJSON() {
        return {
            accountNumber: this.accountNumber,
            userName: this.userName,
            accountType: this.accountType,
            balance: this.balance
        };
    }
    /**
     * Method to deposit amount to an account
     * 
     * @param {number} accountNumberInput - Inputted account number to deposit to.
     * @param {number} amount - Amount to be deposited.
     */
    static deposit(accountNumberInput, amount) {
        if(amount <= 0) {
            throw new InvalidAmountEntered();
        }

        // Make sure account number inputted exists
        const accountExists = checkIfAccountExists(accountNumberInput);

        if(!accountExists) {
            throw new InvalidAccountEntered();
        }

        const accountIndex = findAccountIndex(accountNumberInput);

        // Update account balance        
        accountsArray[accountIndex].balance += amount;

        // Update account json
        updateAccounts();

        Transaction.createNewTransaction("Deposit", amount, accountNumberInput);

        // Update transaction json
        updateTransactions();

        console.log(`Deposit to Account #${accountNumberInput} - $${amount.toFixed(2)} | Successful`);
    }

    /**
     * Method to withdraw amount from an account
     * 
     * @param {number} accountNumberInput - Inputted account number to withdraw from.
     * @param {number} amount - Amount to be withdrawn.
     */
    static withdraw(accountNumberInput, amount) {
        if(amount <= 0) {
            throw new InvalidAmountEntered();    
        }

        // Make sure account number inputted exists
        const accountExists = checkIfAccountExists(accountNumberInput);

        if(!accountExists) {
            throw new InvalidAccountEntered();
        }

        const accountIndex = findAccountIndex(accountNumberInput);

        if((accountsArray[accountIndex].balance - amount) < 0) {
            throw new InvalidWithdrawalAmount();
        }

        // Update account balance        
        accountsArray[accountIndex].balance -= amount;

        // Update account json
        updateAccounts();

        Transaction.createNewTransaction("Withdrawal", amount, accountNumberInput);

        // Update transaction json
        updateTransactions();

        console.log(`Withdrawal from Account #${accountNumberInput} - $${amount.toFixed(2)} | Successful`);
    }

    /**
     * Method to transfer balances.
     * 
     * @param {number} accountNumberTransferOut - Account number transferring money out of.
     * @param {number} accountNumberTransferIn - Account number money being transferred into.
     * @param {number} amount - Amount being transferred between accounts.
     */
    static transfer(accountNumberTransferOut, accountNumberTransferIn, amount) {
        if(amount <= 0) {
            throw new InvalidAmountEntered();    
        }

        // Make sure accounts inputted exist
        const accountTransferOutExists = checkIfAccountExists(accountNumberTransferOut);
        const accountTransferInExists = checkIfAccountExists(accountNumberTransferIn);

        if(!accountTransferOutExists || !accountTransferInExists) {
            throw new InvalidAccountEntered();
        }

        const accountTransferOutIndex = findAccountIndex(accountNumberTransferOut);
        const accountTransferInIndex = findAccountIndex(accountNumberTransferIn);

        accountsArray[accountTransferOutIndex].balance -= amount;
        accountsArray[accountTransferInIndex].balance += amount;

        // Update accounts json
        updateAccounts();

        Transaction.createNewTransaction("Transfer Out", amount, accountNumberTransferOut);
        Transaction.createNewTransaction("Transfer In", amount, accountNumberTransferIn);

        // Update transaction json
        updateTransactions();

        console.log(`Transfer from Account #${accountNumberTransferOut} to Account #${accountNumberTransferIn} for $${amount.toFixed(2)} | Successful`);
    }

    /**
     * Static method to create a new user's account
     * 
     * @param {string} userName - The name the user wants associated with the account.
     * @param {string} accountType - The account type (ie. savings, investment, etc.).
     */
    static createAccount(userName, accountType) {
        const newAccount = new Account(userName, accountType);

        accountsArray.push(newAccount);

        console.log(`Account #${newAccount.accountNumber} was created successfully.`);

        // Update account json
        updateAccounts();
    }

    /**
     * Static method to print all accounts
     */
    static printAccounts() {
        console.log("--- Account(s) ---");
        accountsArray.forEach(account => {
            console.log(`Account: #${account.accountNumber} | Account name: ${account.userName} | Account Type: ${account.accountType} | Balance: $${account.balance.toFixed(2)}`);
        });
    }

    /**
     * Method to print a specific account to the CLI.
     * 
     * @param {number} accountNumberToPrint - Inputted account number that is to be printed.
     */
    static printSpecificAccount(accountNumberToPrint) {
        // Make sure account number inputted exists
        const accountExists = checkIfAccountExists(accountNumberToPrint);

        if(!accountExists) {
            throw new InvalidAccountEntered();
        }

        const accountIndex = findAccountIndex(accountNumberToPrint);

        console.log("--- Account Information ---");
        console.log(`Account: #${accountsArray[accountIndex].accountNumber} | Account name: ${accountsArray[accountIndex].userName} | Account Type: ${accountsArray[accountIndex].accountType} | Balance: $${accountsArray[accountIndex].balance.toFixed(2)}`);
    }
}